//Define the structure of quiz data in database 

import mongoose from "mongoose";

//Define Schema
const questionSchema = new mongoose.Schema({
    question:String,
    options:[String],
    correctAnswer:String
});

// const quizSchema = new mongoose.Schema({
//     title:{type:String,required:true},
//     questions:[
//         {
//             question:{type:String,required:true},
//             options:[String],
//             answer:{type:String,required:true}
//         }
//     ],
// },{ timestamps: true })  //this automatically adds two fields createdAt and updatedAt helps to track when quiz was created or updated 

const quizSchema = new mongoose.Schema({
  topic: { type: String, required: true },
  questions: { type: Array, required: true }, // Array of questions generated by AI
  createdAt: { type: Date, default: Date.now }
});


const Quiz = mongoose.model('Quiz', quizSchema);  //convert schema into model
export default Quiz;